In [113]:
import numpy as np

In [114]:
# np.array

r = np.array([3,6,9])
print(type(r))

<class 'numpy.ndarray'>


In [115]:
# 2D & 3D array

j = np.array([[3,6,9,], [11,14,17]])
print(j)

q = np.array([[1,2,3], [4,5,6],[7,8,9]])
print(q)

[[ 3  6  9]
 [11 14 17]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [116]:
''' 1D arr is vector
    2D arr is vector
    3D arr is tensor '''


' 1D arr is vector\n    2D arr is vector \n    3D arr is tensor '

In [117]:
# dtype

np.array([1,2,3],dtype=float) # float value

array([1., 2., 3.])

In [118]:
# np.arange

np.arange(1,14)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [119]:
# with reshape

np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [120]:
# np.ones and zeros

np.ones([3,6])



array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [121]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [122]:
# np.random

np.random.random([3,4])

array([[0.44839747, 0.99973256, 0.64841784, 0.69310952],
       [0.78839474, 0.13522479, 0.83822152, 0.03278192],
       [0.27545568, 0.02807313, 0.09607728, 0.20594998]])

In [123]:
# np.linspace

np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [124]:
# np.indentity

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [125]:
## Array attributes

In [126]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [127]:
# ndim

a3.ndim

3

In [128]:
# shape

print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [129]:
# size

print(a3.size)
a3

8


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [130]:
# itemsize

a3.itemsize

8

In [131]:
# dtype

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


In [132]:
## Changing datatypes

In [133]:
#astype

a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [134]:
## Array operations

In [135]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [136]:
# scaler operations

# arithmatic
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [137]:
# relational

a2 > 12

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [138]:
# vector operations
# arithmatic
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [139]:
2 ** 3

8

In [140]:
## Array functions

a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[74., 13., 70.],
       [82., 18.,  2.],
       [16., 49., 44.]])

In [141]:
# max/min/sum/prod
# 0 - > col and 1 - > row
np.prod(a1,axis=0)

array([97088., 11466.,  6160.])

In [142]:
# mean/median/std/var

np.mean(a1)

40.888888888888886

In [143]:
# trigonomatric functions

np.sin(a1)

array([[-0.98514626,  0.42016704,  0.77389068],
       [ 0.31322878, -0.75098725,  0.90929743],
       [-0.28790332, -0.95375265,  0.01770193]])

In [144]:
# dot product

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [145]:
# log and exponents

np.exp(a1)

array([[1.37338298e+32, 4.42413392e+05, 2.51543867e+30],
       [4.09399696e+35, 6.56599691e+07, 7.38905610e+00],
       [8.88611052e+06, 1.90734657e+21, 1.28516001e+19]])

In [146]:
## Indexing and Slicing

a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [147]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [148]:
a1[-1]

9

In [149]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [150]:
a2[1,0]

4

In [151]:
## Iterating

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [152]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [153]:
a3[0,1,0]

2

In [154]:
a3[0,0,0]

0

In [155]:
a3[1,1,0]

6

In [156]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
# Slicing

a1[6:9]

array([6, 7, 8])

In [158]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [159]:
a2[0,:]

array([0, 1, 2, 3])

In [160]:
a2[:,2]

array([ 2,  6, 10])

In [161]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [162]:
a2[::3,::3]

array([[0, 3]])

In [163]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [164]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [165]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [166]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [167]:
## Iterating

In [171]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [172]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [168]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [173]:
for i in a2:
  print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [169]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [174]:
for i in a3:
  print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [177]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [175]:
## Reshaping

In [179]:
# traspose

np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [180]:
# ravel

a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [181]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [182]:
## Stacking

In [184]:
# horizontal stacking

a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [185]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [186]:
# vertical stacking

np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [187]:
## Splitting

In [189]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [191]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
# verical splitting

In [192]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [193]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]